version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/main.go
    id: default
    flags: -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.Commit={{ .Env.COMMIT }}
    binary: ding
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    ids: [default]
    formats: ["binary"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Commit }}_{{ .Os }}_{{ .Arch }}"
  - id: archive
    ids: [default]
    formats: ["zip", "tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Commit }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: default
    ids: [default]
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Commit }}_{{ .Os }}_{{ .Arch }}"
    vendor: "bugwz"
    maintainer: "bugwz <xbugwz@gmail.com>"
    homepage: "https://bugwz.com"
    description: "Ding Project"
    license: "MIT"

brews:
  - name: ding
    ids: [binary]
    commit_author:
      name: bugwz
      email: xbugwz@gmail.com
    directory: Formula
    homepage: https://github.com/bugwz/ding
    description: "Cross-platform CLI tool"
    install: |
      bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
      mkdir_p "#{etc}/ding"
      cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
    test: system "#{bin}/ding --version"
    repository:
      owner: bugwz
      name: homebrew-tap
