version: 2

before:
  hooks:
    - go mod download

builds:
  - id: "default"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go
    flags: -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.commit={{ .Env.COMMIT }}
    binary: ding_{{.Os}}_{{.Arch}}

archives:
  - id: binary_archive
    formats: [ "zip", "tar.gz", "binary"]
    name_template: 'ding_{{.Os}}_{{.Arch}}'

nfpms:
  - id: "default"
    ids: [ default ]
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: "bugwz"
    maintainer: "bugwz <xbugwz@gmail.com>"
    homepage: "https://bugwz.com"
    description: "Ding Project"
    license: "MIT"

brews:
  - name: ding
    ids: [ default ]
    repository:
      owner: bugwz
      name: homebrew-tap
    commit_author:
      name: ci-bot
      email: ci@example.com
    directory: Formula
    homepage: http://github.com/bugwz/ding
    description: "Cross-platform CLI tool"
    install: |
      bin.install "ding_{{.Os}}_{{.Arch}}" => "ding"
      cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
    test: system "#{bin}/ding --version"