before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/main.go
    goarch:
      - amd64
      - arm64
    flags: -trimpath
    ldflags:
      - -s -w -X main.Version=$(shell cat ./Version)

archives:
  - id: binary_archive
    format: binary
    name_template: 'ding_{{.Os}}_{{.Arch}}'

brews:
  - name: ding
    tap:
      owner: bugwz
      name: homebrew-tap
    # url: https://github.com/bugwz/homebrew-tap
    commit_author:
      name: ci-bot
      email: ci@example.com
    folder: Formula
    homepage: https://github.com/bugwz/ding
    description: Cross-platform CLI tool
    install: |
      bin.install "ding_darwin_#{Hardware::CPU.intel? ? "amd64" : "arm64"}" => "ding"
      mkdir_p "#{etc}/ding"
      cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
    test: system "#{bin}/ding --version"