version: 2

before:
  hooks:
    - go mod download

builds:
  -
    id: ding-build
    main: ./cmd/main.go
    binary: ding
    flags: -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Env.VERSION }} -X main.Commit={{ .Env.COMMIT }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 6
    goarm64:
      - v8.0
    goamd64:
      - v1

archives:
  -
    id: ding-binary
    ids:
      - ding-build
    formats: ["binary"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  -
    id: ding-archive
    ids:
      - ding-build
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: default
    ids:
      - ding-build
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: "bugwz"
    maintainer: "bugwz <xbugwz@gmail.com>"
    homepage: "https://bugwz.com"
    description: "Ding Project"
    license: "MIT"

brews:
  -
    name: ding
    alternative_names:
      - ding@{{ .Version }}
      - ding@{{ .Major }}
    ids:
      - ding-binary
    goarm: 6
    goamd64: v1
    url_headers:
      - "Accept: application/octet-stream"
      - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'
    commit_author:
      name: bugwz
      email: xbugwz@gmail.com
    directory: Formula
    homepage: https://github.com/bugwz/ding
    description: "Ding CLI tool"
    install: |
      bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
      mkdir_p "#{etc}/ding"
      cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
    test: system "#{bin}/ding --version"
    repository:
      owner: bugwz
      name: ding
      branch: homebrew-tap
