# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Ding CLI tool"
  homepage "https://github.com/bugwz/ding"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_darwin_amd64",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "d309e4c0600a232f599288827495516ad5bdc1a3549701654f3092860ed5460e"

      def install
        bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
        mkdir_p "#{etc}/ding"
        cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_darwin_arm64",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "59df0291eb4825d93544e930df315bcb96606c8edd44d3f96484efffddffc8fb"

      def install
        bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
        mkdir_p "#{etc}/ding"
        cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_amd64",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "928d0bad3d5d2adacf189da333916a20f807c292fd43f633ee967a725a32e192"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_arm",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "eaae0b65c062712b207ff212d47535d94a2170d6a861685ad8078c038b5b5b66"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_arm64",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "0cbfd86ca38d71345ec2abff15ece022ac152f773657d724fbb83272f8e41ced"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
  end

  test do
    system "#{bin}/ding --version"
  end
end
