# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Ding CLI tool"
  homepage "https://github.com/bugwz/ding"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_darwin_amd64",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "0ebe483d6ccfa436649ddb7c951afa3d246146200e22754563e732e9f309e372"

      def install
        bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
        mkdir_p "#{etc}/ding"
        cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_darwin_arm64",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "006e200665a7c1574236e5ef913daa87228583d0cef576ec7f949f9d939eb5d8"

      def install
        bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
        mkdir_p "#{etc}/ding"
        cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_amd64",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "b2ebd17b11b192ee1f3e6502986bb6833fd4f64c42aa0f116f745f627ab1ecc6"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_arm",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "de82f64456512b2286d4cb3f13d55bd2f6189828fe726ec9ca8a73e43185b486"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bugwz/ding/releases/download/v0.0.1/ding_0.0.1_linux_arm64",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "f9f4a3cfd09356f40d31a083ded5a31807aae5c1f9c16cc8959bff14c1dc60ef"

        def install
          bin.install "ding_darwin_#{Hardware::CPU.intel? ? 'amd64' : 'arm64'}" => "ding"
          mkdir_p "#{etc}/ding"
          cp "#{buildpath}/config/default.ini", "#{etc}/ding/default.ini"
        end
      end
    end
  end

  test do
    system "#{bin}/ding --version"
  end
end
